Jng\ActivityBundle\Entity\ActivityStorage:
    type: entity
    table: activity_storage
    fields:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
        start:
            type: datetime
            length: null
        end:
            type: datetime
            length: null
    manyToOne:
        activity:
            targetEntity: Activity
            joinColumn:
                name: activity_id
                referencedColumnName: id
        task:
            targetEntity: Task
            joinColumn:
                name: task_id
                referencedColumnName: id            
            
    lifecycleCallbacks: 
      prePersist: [ setStartValue ]
