Jng\ActivityBundle\Entity\Activity:
    type: entity
    table: activity
    fields:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
        name:
            type: string
            length: '255'
        created_at:
            type: datetime
        updated_at:
            type: datetime
            nullable: true
    manyToOne:
        customer:
            targetEntity: Customer
            joinColumn:
                name: customer_id
                referencedColumnName: id  
            orderBy:
                name: ASC 
            cascade: ["persist"]    
    lifecycleCallbacks:
        prePersist: [ setCreatedAtValue ]
        preUpdate: [ setUpdatedAtValue ]
