Jng\ActivityBundle\Entity\ActivityStorage:
    type: entity
    table: activity_storage
    repositoryClass: Jng\ActivityBundle\Entity\Repository\ActivityStorageRepository
    fields:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
        start:
            type: datetime
            length: null
        end:
            type: datetime
            length: null
            nullable: true
    manyToOne:
        activity:
            targetEntity: Activity
            joinColumn:
                name: activity_id
                referencedColumnName: id
            orderBy:
                name: ASC    
            cascade: ["persist"]     
        task:
            targetEntity: Task
            joinColumn:
                name: task_id
                referencedColumnName: id    
            orderBy:
                name: ASC  
            cascade: ["persist"]    
        user:
            targetEntity: Jng\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id  
            orderBy:
                name: ASC 
            cascade: ["persist"]              
