Jng\ActivityBundle\Entity\Customer:
    type: entity
    table: customer
    repositoryClass: Jng\ActivityBundle\Entity\Repository\CustomerRepository
    fields:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
        name:
            type: string
            length: '255'
    manyToOne:
        business:
            targetEntity: Business
            joinColumn:
                name: business_id
                referencedColumnName: id  
            orderBy:
                name: ASC   
            cascade: ["persist"]   
        user:
            targetEntity: Jng\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id  
            orderBy:
                name: ASC 
            cascade: ["persist"]              
    lifecycleCallbacks: {  }
