Jng\ActivityBundle\Entity\Task:
    type: entity
    table: task
    repositoryClass: Jng\ActivityBundle\Entity\Repository\TaskRepository
    fields:
        id:
            type: integer
            id: true
            generator: { strategy: AUTO }
        name:
            type: string
            length: '255'
        order_nb:
            type: integer
            length: null
    manyToOne:
        activity:
            targetEntity: Activity
            joinColumn:
                name: activity_id
                referencedColumnName: id   
            orderBy:
                name: ASC                  
            cascade: [remove]    
        user:
            targetEntity: Jng\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id  
            orderBy:
                name: ASC 
            cascade: ["persist"]              
    lifecycleCallbacks: {  }
