activitystorage:
    pattern:  /
    defaults: { _controller: "JngActivityBundle:ActivityStorage:index" }

activitystorage_show:
    pattern:  /{id}/show
    defaults: { _controller: "JngActivityBundle:ActivityStorage:show" }

activitystorage_new:
    pattern:  /new
    defaults: { _controller: "JngActivityBundle:ActivityStorage:new" }

activitystorage_newmanually:
    pattern:  /newmanually
    defaults: { _controller: "JngActivityBundle:ActivityStorage:newmanually" }

activitystorage_create:
    pattern:  /create
    defaults: { _controller: "JngActivityBundle:ActivityStorage:create" }
    requirements: { _method: post }

activitystorage_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "JngActivityBundle:ActivityStorage:edit" }

activitystorage_update:
    pattern:  /{id}/update
    defaults: { _controller: "JngActivityBundle:ActivityStorage:update" }
    requirements: { _method: post|put }

activitystorage_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "JngActivityBundle:ActivityStorage:delete" }
    requirements: { _method: post|delete }
    
activitystorage_stop:
    pattern:  /{id}/stop
    defaults: { _controller: "JngActivityBundle:ActivityStorage:stop" }
    requirements: { _method: post|put }    
    
activitystorage_updatechart:
    pattern:  /updatechart
    defaults: { _controller: "JngActivityBundle:ActivityStorage:updatechart" }
    requirements: { _method: post }  