_welcome:
    pattern:  /today
    defaults: { _controller: JngActivityBundle:Entry:today }

_listActivity:
    pattern:  /list
    defaults: { _controller: JngActivityBundle:Entry:listActivity }
    
_addActivity:
    pattern:  /addActivity
    defaults: { _controller: JngActivityBundle:Entry:addActivity }    

_addActivityStorage:
    pattern:  /addActivityStorage
    defaults: { _controller: JngActivityBundle:Entry:addActivityStorage }  
    
_addBusiness:
    pattern:  /addBusiness
    defaults: { _controller: JngActivityBundle:Entry:addBusiness }  
    
_addCustomer:
    pattern:  /addCustomer
    defaults: { _controller: JngActivityBundle:Entry:addCustomer }  
    
_addTask:
    pattern:  /addTask
    defaults: { _controller: JngActivityBundle:Entry:addTask }      