JngActivityBundle_activity:
        resource: "@JngActivityBundle/Resources/config/routing/activity.yml"
        prefix:   /activity
        
JngActivityBundle_activitystorage:
        resource: "@JngActivityBundle/Resources/config/routing/activitystorage.yml"
        prefix:   /activitystorage       
        
JngActivityBundle_business:
        resource: "@JngActivityBundle/Resources/config/routing/business.yml"
        prefix:   /business    
        
JngActivityBundle_customer:
        resource: "@JngActivityBundle/Resources/config/routing/customer.yml"
        prefix:   /customer

JngActivityBundle_task:
        resource: "@JngActivityBundle/Resources/config/routing/task.yml"
        prefix:   /task
